server:
  port: 8085
spring:
  datasource:
    platform: h2
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  redis:
    database: 2
    host: ****
    port: 6379
    password: 123456

logging:
  level:
    root: INFO
    org:
      hibernate: INFO
    com.study:  DEBUG
